// Generated By db to  class
package db;

public class Activation {

	public static String id = "`activation`.id", code = "`activation`.code",
			userid = "`activation`.userid", tarih = "`activation`.tarih";;

}
