// Generated By db to  class
package db;

public class DB {

	public static String activation = "`activation`", catcount = "`catcount`",
			category = "`category`", firsatproduct = "`firsatproduct`",
			gridfield = "`gridfield`", keyword = "`keyword`",
			mailcontent = "`mailcontent`", product = "`product`",
			productcategory = "`productcategory`",
			productphoto = "`productphoto`", prostate = "`prostate`",
			resetpassword = "`resetpassword`", state = "`state`",
			talep = "`talep`", test = "`test`", user = "`user`";;

}
