// Generated By db to  class
package db;

public class Gridfield  {

public static String id="`gridfield`.id",tableName="`gridfield`.tableName",header="`gridfield`.header",name="`gridfield`.name",state="`gridfield`.state";;

}
	
