// Generated By db to  class
package db;

public class Product {

	public static String id = "`product`.id", userid = "`product`.userid",
			pname = "`product`.pname", content = "`product`.content",
			pstate = "`product`.pstate", quantity = "`product`.quantity",
			price = "`product`.price", expiredate = "`product`.expiredate",
			keywords = "`product`.keywords", file = "`product`.file",
			adet = "`product`.adet", kg = "`product`.kg", m3 = "`product`.m3",
			kalem = "`product`.kalem", pprice = "`product`.pprice";;

}
