// Generated By db to  class
package db;

public class Productcategory  {

public static String id="`productcategory`.id",productId="`productcategory`.productId",categoryId="`productcategory`.categoryId";;

}
	
