// Generated By db to  class
package db;

public class Resetpassword  {

public static String id="`resetpassword`.id",code="`resetpassword`.code",userid="`resetpassword`.userid",tarih="`resetpassword`.tarih";;

}
	
