// Generated By db to  class
package db;

public class Talep  {

public static String id="`talep`.id",productid="`talep`.productid",userid="`talep`.userid",name="`talep`.name",email="`talep`.email",gsm="`talep`.gsm",notes="`talep`.notes",state="`talep`.state",tarih="`talep`.tarih";;

}
	
