// Generated By db to  class
package db;

public class User  {

public static String id="`user`.id",email="`user`.email",password="`user`.password",firmaname="`user`.firmaname",uname="`user`.uname",cepno="`user`.cepno",sabitno="`user`.sabitno",address="`user`.address",city="`user`.city",website="`user`.website",vergidaire="`user`.vergidaire",vergino="`user`.vergino",state="`user`.state",uuid="`user`.uuid";;

}
	
